print('This is an appended line to the file.')
print('after deleting')
print('After deleting')
print('After deleting')
print('After deleting')
print('After deleting')
print('After deleting')
print('After deleting')
print('After deleting')
